# Generated by Django 4.2.7 on 2024-03-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_farmproduct_rename_price_cartitem_total_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmProduct',
            new_name='Product',
        ),
    ]
